service: google-sites-slack-notification

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"

plugins:
  - serverless-prune-plugin
  - "@vingle/serverless-tag-plugin"

custom:
  prune:
    automatic: true
    number: 5

package:
  artifact: dst.zip

functions:
  sync:
    handler: sync.handler
    memorySize: 128
    timeout: 60
    events:
    - schedule:
        rate: cron(0/5 * * * ? *) # every 5 minutes


resources:
  Resources:
    SyncLogGroup:
      Properties:
        RetentionInDays: "30"
